package com.fss.saber.adapter.jpa;
// Generated 24-Dec-2022, 8:01:28 pm by Hibernate Tools 4.3.6.Final

import java.math.BigInteger;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * UserAthnMstr generated by hbm2java
 */
@Entity
@Table(name = "USER_ATHN_MSTR")
public class UserAthnMstr implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String userId;
	private BigInteger seqId;
	private String userMobNmbr;
	private String userEmailId;
	private String userRole;
	private String userPassword;
	private String userStatus;
	private String userPasswordStatus;
	private Date createdOn;
	private Date modifiedOn;
	private String userMenuGrp;
	private String userOldPassword1;
	private String userOldPassword2;
	private String userOldPassword3;
	private String userPasswordCnt;
	private String onboardedBy;
	private String approvedBy;
	private String admUserRoleId;
	private Date pswdMdfdDt;
	private Set<UserAdditionalDetails> userAdditionalDetailses = new HashSet<UserAdditionalDetails>(0);

	public UserAthnMstr() {
	}

	public UserAthnMstr(String userId, BigInteger seqId) {
		this.userId = userId;
		this.seqId = seqId;
	}

	public UserAthnMstr(String userId, BigInteger seqId, String userMobNmbr, String userEmailId, String userRole,
			String userPassword, String userStatus, String userPasswordStatus, Date createdOn, Date modifiedOn,
			String userMenuGrp, String userOldPassword1, String userOldPassword2, String userOldPassword3,
			String userPasswordCnt, String onboardedBy, String approvedBy, String admUserRoleId, Date pswdMdfdDt,
			Set<UserAdditionalDetails> userAdditionalDetailses) {
		this.userId = userId;
		this.seqId = seqId;
		this.userMobNmbr = userMobNmbr;
		this.userEmailId = userEmailId;
		this.userRole = userRole;
		this.userPassword = userPassword;
		this.userStatus = userStatus;
		this.userPasswordStatus = userPasswordStatus;
		this.createdOn = createdOn;
		this.modifiedOn = modifiedOn;
		this.userMenuGrp = userMenuGrp;
		this.userOldPassword1 = userOldPassword1;
		this.userOldPassword2 = userOldPassword2;
		this.userOldPassword3 = userOldPassword3;
		this.userPasswordCnt = userPasswordCnt;
		this.onboardedBy = onboardedBy;
		this.approvedBy = approvedBy;
		this.admUserRoleId = admUserRoleId;
		this.pswdMdfdDt = pswdMdfdDt;
		this.userAdditionalDetailses = userAdditionalDetailses;
	}

	@Id

	@Column(name = "USER_ID", unique = true, nullable = false, length = 50)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "SEQ_ID", nullable = false, precision = 22, scale = 0)
	public BigInteger getSeqId() {
		return this.seqId;
	}

	public void setSeqId(BigInteger seqId) {
		this.seqId = seqId;
	}

	@Column(name = "USER_MOB_NMBR", length = 50)
	public String getUserMobNmbr() {
		return this.userMobNmbr;
	}

	public void setUserMobNmbr(String userMobNmbr) {
		this.userMobNmbr = userMobNmbr;
	}

	@Column(name = "USER_EMAIL_ID", length = 100)
	public String getUserEmailId() {
		return this.userEmailId;
	}

	public void setUserEmailId(String userEmailId) {
		this.userEmailId = userEmailId;
	}

	@Column(name = "USER_ROLE", length = 50)
	public String getUserRole() {
		return this.userRole;
	}

	public void setUserRole(String userRole) {
		this.userRole = userRole;
	}

	@Column(name = "USER_PASSWORD", length = 1000)
	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	@Column(name = "USER_STATUS", length = 20)
	public String getUserStatus() {
		return this.userStatus;
	}

	public void setUserStatus(String userStatus) {
		this.userStatus = userStatus;
	}

	@Column(name = "USER_PASSWORD_STATUS", length = 10)
	public String getUserPasswordStatus() {
		return this.userPasswordStatus;
	}

	public void setUserPasswordStatus(String userPasswordStatus) {
		this.userPasswordStatus = userPasswordStatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATED_ON", length = 7)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODIFIED_ON", length = 7)
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	@Column(name = "USER_MENU_GRP", length = 50)
	public String getUserMenuGrp() {
		return this.userMenuGrp;
	}

	public void setUserMenuGrp(String userMenuGrp) {
		this.userMenuGrp = userMenuGrp;
	}

	@Column(name = "USER_OLD_PASSWORD1", length = 1000)
	public String getUserOldPassword1() {
		return this.userOldPassword1;
	}

	public void setUserOldPassword1(String userOldPassword1) {
		this.userOldPassword1 = userOldPassword1;
	}

	@Column(name = "USER_OLD_PASSWORD2", length = 1000)
	public String getUserOldPassword2() {
		return this.userOldPassword2;
	}

	public void setUserOldPassword2(String userOldPassword2) {
		this.userOldPassword2 = userOldPassword2;
	}

	@Column(name = "USER_OLD_PASSWORD3", length = 1000)
	public String getUserOldPassword3() {
		return this.userOldPassword3;
	}

	public void setUserOldPassword3(String userOldPassword3) {
		this.userOldPassword3 = userOldPassword3;
	}

	@Column(name = "USER_PASSWORD_CNT", length = 10)
	public String getUserPasswordCnt() {
		return this.userPasswordCnt;
	}

	public void setUserPasswordCnt(String userPasswordCnt) {
		this.userPasswordCnt = userPasswordCnt;
	}

	@Column(name = "ONBOARDED_BY", length = 50)
	public String getOnboardedBy() {
		return this.onboardedBy;
	}

	public void setOnboardedBy(String onboardedBy) {
		this.onboardedBy = onboardedBy;
	}

	@Column(name = "APPROVED_BY", length = 50)
	public String getApprovedBy() {
		return this.approvedBy;
	}

	public void setApprovedBy(String approvedBy) {
		this.approvedBy = approvedBy;
	}

	@Column(name = "ADM_USER_ROLE_ID", length = 50)
	public String getAdmUserRoleId() {
		return this.admUserRoleId;
	}

	public void setAdmUserRoleId(String admUserRoleId) {
		this.admUserRoleId = admUserRoleId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "PSWD_MDFD_DT", length = 7)
	public Date getPswdMdfdDt() {
		return this.pswdMdfdDt;
	}

	public void setPswdMdfdDt(Date pswdMdfdDt) {
		this.pswdMdfdDt = pswdMdfdDt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userAthnMstr")
	public Set<UserAdditionalDetails> getUserAdditionalDetailses() {
		return this.userAdditionalDetailses;
	}

	public void setUserAdditionalDetailses(Set<UserAdditionalDetails> userAdditionalDetailses) {
		this.userAdditionalDetailses = userAdditionalDetailses;
	}

}
