package com.fss.saber.adapter.jpa;
// Generated 24-Dec-2022, 8:01:28 pm by Hibernate Tools 4.3.6.Final

import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * UserAdditionalDetails generated by hbm2java
 */
@Entity
@Table(name = "USER_ADDITIONAL_DETAILS")
public class UserAdditionalDetails implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private UserAdditionalDetailsId id;
	private UserAthnMstr userAthnMstr;

	public UserAdditionalDetails() {
	}

	public UserAdditionalDetails(UserAdditionalDetailsId id, UserAthnMstr userAthnMstr) {
		this.id = id;
		this.userAthnMstr = userAthnMstr;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "seqId", column = @Column(name = "SEQ_ID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "userId", column = @Column(name = "USER_ID", nullable = false, length = 50)),
			@AttributeOverride(name = "firstName", column = @Column(name = "FIRST_NAME", length = 50)),
			@AttributeOverride(name = "middleName", column = @Column(name = "MIDDLE_NAME", length = 50)),
			@AttributeOverride(name = "lastName", column = @Column(name = "LAST_NAME", length = 50)),
			@AttributeOverride(name = "userName", column = @Column(name = "USER_NAME", length = 50)),
			@AttributeOverride(name = "gender", column = @Column(name = "GENDER", length = 10)),
			@AttributeOverride(name = "dob", column = @Column(name = "DOB", length = 30)),
			@AttributeOverride(name = "fatherName", column = @Column(name = "FATHER_NAME", length = 50)),
			@AttributeOverride(name = "addrLneOne", column = @Column(name = "ADDR_LNE_ONE", length = 250)),
			@AttributeOverride(name = "addrLneTwo", column = @Column(name = "ADDR_LNE_TWO", length = 250)),
			@AttributeOverride(name = "locality", column = @Column(name = "LOCALITY", length = 50)),
			@AttributeOverride(name = "state", column = @Column(name = "STATE", length = 50)),
			@AttributeOverride(name = "district", column = @Column(name = "DISTRICT", length = 50)),
			@AttributeOverride(name = "pincode", column = @Column(name = "PINCODE", length = 10)),
			@AttributeOverride(name = "createdOn", column = @Column(name = "CREATED_ON", length = 7)),
			@AttributeOverride(name = "modifiedOn", column = @Column(name = "MODIFIED_ON", length = 7)),
			@AttributeOverride(name = "profAdsDocName", column = @Column(name = "PROF_ADS_DOC_NAME", length = 50)),
			@AttributeOverride(name = "profAdsDoc", column = @Column(name = "PROF_ADS_DOC")),
			@AttributeOverride(name = "profAdsType", column = @Column(name = "PROF_ADS_TYPE", length = 50)),
			@AttributeOverride(name = "panNumber", column = @Column(name = "PAN_NUMBER", length = 1000)),
			@AttributeOverride(name = "panDocName", column = @Column(name = "PAN_DOC_NAME", length = 50)),
			@AttributeOverride(name = "panDoc", column = @Column(name = "PAN_DOC")),
			@AttributeOverride(name = "bnkProfName", column = @Column(name = "BNK_PROF_NAME", length = 50)),
			@AttributeOverride(name = "bnkProfDoc", column = @Column(name = "BNK_PROF_DOC")),
			@AttributeOverride(name = "bnkProfType", column = @Column(name = "BNK_PROF_TYPE", length = 50)),
			@AttributeOverride(name = "profilePicName", column = @Column(name = "PROFILE_PIC_NAME", length = 50)),
			@AttributeOverride(name = "profilePicDoc", column = @Column(name = "PROFILE_PIC_DOC")),
			@AttributeOverride(name = "masterFransId", column = @Column(name = "MASTER_FRANS_ID", length = 50)),
			@AttributeOverride(name = "clusterHeadId", column = @Column(name = "CLUSTER_HEAD_ID", length = 50)),
			@AttributeOverride(name = "bankHolderName", column = @Column(name = "BANK_HOLDER_NAME", length = 50)),
			@AttributeOverride(name = "bankName", column = @Column(name = "BANK_NAME", length = 50)),
			@AttributeOverride(name = "bankAcctNmbr", column = @Column(name = "BANK_ACCT_NMBR", length = 50)),
			@AttributeOverride(name = "bankIfscCode", column = @Column(name = "BANK_IFSC_CODE", length = 50)),
			@AttributeOverride(name = "agentType", column = @Column(name = "AGENT_TYPE", length = 50)),
			@AttributeOverride(name = "relationWithCompany", column = @Column(name = "RELATION_WITH_COMPANY", length = 10)),
			@AttributeOverride(name = "remarks", column = @Column(name = "REMARKS", length = 100)),
			@AttributeOverride(name = "employeeNo", column = @Column(name = "EMPLOYEE_NO", length = 50)),
			@AttributeOverride(name = "phyHandicapped", column = @Column(name = "PHY_HANDICAPPED", length = 10)),
			@AttributeOverride(name = "category", column = @Column(name = "CATEGORY", length = 30)),
			@AttributeOverride(name = "deliveryCategory", column = @Column(name = "DELIVERY_CATEGORY", length = 50)) })
	public UserAdditionalDetailsId getId() {
		return this.id;
	}

	public void setId(UserAdditionalDetailsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ID", nullable = false, insertable = false, updatable = false)
	public UserAthnMstr getUserAthnMstr() {
		return this.userAthnMstr;
	}

	public void setUserAthnMstr(UserAthnMstr userAthnMstr) {
		this.userAthnMstr = userAthnMstr;
	}

}
