package com.fss.saber.adapter.jpa;
// Generated 24-Dec-2022, 8:01:28 pm by Hibernate Tools 4.3.6.Final

import java.math.BigInteger;
import java.sql.Blob;
import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * UserAdditionalDetailsId generated by hbm2java
 */
@Embeddable
public class UserAdditionalDetailsId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigInteger seqId;
	private String userId;
	private String firstName;
	private String middleName;
	private String lastName;
	private String userName;
	private String gender;
	private String dob;
	private String fatherName;
	private String addrLneOne;
	private String addrLneTwo;
	private String locality;
	private String state;
	private String district;
	private String pincode;
	private Date createdOn;
	private Date modifiedOn;
	private String profAdsDocName;
	private Blob profAdsDoc;
	private String profAdsType;
	private String panNumber;
	private String panDocName;
	private Blob panDoc;
	private String bnkProfName;
	private Blob bnkProfDoc;
	private String bnkProfType;
	private String profilePicName;
	private Blob profilePicDoc;
	private String masterFransId;
	private String clusterHeadId;
	private String bankHolderName;
	private String bankName;
	private String bankAcctNmbr;
	private String bankIfscCode;
	private String agentType;
	private String relationWithCompany;
	private String remarks;
	private String employeeNo;
	private String phyHandicapped;
	private String category;
	private String deliveryCategory;

	public UserAdditionalDetailsId() {
	}

	public UserAdditionalDetailsId(BigInteger seqId, String userId) {
		this.seqId = seqId;
		this.userId = userId;
	}

	public UserAdditionalDetailsId(BigInteger seqId, String userId, String firstName, String middleName,
			String lastName, String userName, String gender, String dob, String fatherName, String addrLneOne,
			String addrLneTwo, String locality, String state, String district, String pincode, Date createdOn,
			Date modifiedOn, String profAdsDocName, Blob profAdsDoc, String profAdsType, String panNumber,
			String panDocName, Blob panDoc, String bnkProfName, Blob bnkProfDoc, String bnkProfType,
			String profilePicName, Blob profilePicDoc, String masterFransId, String clusterHeadId,
			String bankHolderName, String bankName, String bankAcctNmbr, String bankIfscCode, String agentType,
			String relationWithCompany, String remarks, String employeeNo, String phyHandicapped, String category,
			String deliveryCategory) {
		this.seqId = seqId;
		this.userId = userId;
		this.firstName = firstName;
		this.middleName = middleName;
		this.lastName = lastName;
		this.userName = userName;
		this.gender = gender;
		this.dob = dob;
		this.fatherName = fatherName;
		this.addrLneOne = addrLneOne;
		this.addrLneTwo = addrLneTwo;
		this.locality = locality;
		this.state = state;
		this.district = district;
		this.pincode = pincode;
		this.createdOn = createdOn;
		this.modifiedOn = modifiedOn;
		this.profAdsDocName = profAdsDocName;
		this.profAdsDoc = profAdsDoc;
		this.profAdsType = profAdsType;
		this.panNumber = panNumber;
		this.panDocName = panDocName;
		this.panDoc = panDoc;
		this.bnkProfName = bnkProfName;
		this.bnkProfDoc = bnkProfDoc;
		this.bnkProfType = bnkProfType;
		this.profilePicName = profilePicName;
		this.profilePicDoc = profilePicDoc;
		this.masterFransId = masterFransId;
		this.clusterHeadId = clusterHeadId;
		this.bankHolderName = bankHolderName;
		this.bankName = bankName;
		this.bankAcctNmbr = bankAcctNmbr;
		this.bankIfscCode = bankIfscCode;
		this.agentType = agentType;
		this.relationWithCompany = relationWithCompany;
		this.remarks = remarks;
		this.employeeNo = employeeNo;
		this.phyHandicapped = phyHandicapped;
		this.category = category;
		this.deliveryCategory = deliveryCategory;
	}

	@Column(name = "SEQ_ID", nullable = false, precision = 22, scale = 0)
	public BigInteger getSeqId() {
		return this.seqId;
	}

	public void setSeqId(BigInteger seqId) {
		this.seqId = seqId;
	}

	@Column(name = "USER_ID", nullable = false, length = 50)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "FIRST_NAME", length = 50)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "MIDDLE_NAME", length = 50)
	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	@Column(name = "LAST_NAME", length = 50)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "USER_NAME", length = 50)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "GENDER", length = 10)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "DOB", length = 30)
	public String getDob() {
		return this.dob;
	}

	public void setDob(String dob) {
		this.dob = dob;
	}

	@Column(name = "FATHER_NAME", length = 50)
	public String getFatherName() {
		return this.fatherName;
	}

	public void setFatherName(String fatherName) {
		this.fatherName = fatherName;
	}

	@Column(name = "ADDR_LNE_ONE", length = 250)
	public String getAddrLneOne() {
		return this.addrLneOne;
	}

	public void setAddrLneOne(String addrLneOne) {
		this.addrLneOne = addrLneOne;
	}

	@Column(name = "ADDR_LNE_TWO", length = 250)
	public String getAddrLneTwo() {
		return this.addrLneTwo;
	}

	public void setAddrLneTwo(String addrLneTwo) {
		this.addrLneTwo = addrLneTwo;
	}

	@Column(name = "LOCALITY", length = 50)
	public String getLocality() {
		return this.locality;
	}

	public void setLocality(String locality) {
		this.locality = locality;
	}

	@Column(name = "STATE", length = 50)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "DISTRICT", length = 50)
	public String getDistrict() {
		return this.district;
	}

	public void setDistrict(String district) {
		this.district = district;
	}

	@Column(name = "PINCODE", length = 10)
	public String getPincode() {
		return this.pincode;
	}

	public void setPincode(String pincode) {
		this.pincode = pincode;
	}

	@Column(name = "CREATED_ON", length = 7)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "MODIFIED_ON", length = 7)
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	@Column(name = "PROF_ADS_DOC_NAME", length = 50)
	public String getProfAdsDocName() {
		return this.profAdsDocName;
	}

	public void setProfAdsDocName(String profAdsDocName) {
		this.profAdsDocName = profAdsDocName;
	}

	@Column(name = "PROF_ADS_DOC")
	public Blob getProfAdsDoc() {
		return this.profAdsDoc;
	}

	public void setProfAdsDoc(Blob profAdsDoc) {
		this.profAdsDoc = profAdsDoc;
	}

	@Column(name = "PROF_ADS_TYPE", length = 50)
	public String getProfAdsType() {
		return this.profAdsType;
	}

	public void setProfAdsType(String profAdsType) {
		this.profAdsType = profAdsType;
	}

	@Column(name = "PAN_NUMBER", length = 1000)
	public String getPanNumber() {
		return this.panNumber;
	}

	public void setPanNumber(String panNumber) {
		this.panNumber = panNumber;
	}

	@Column(name = "PAN_DOC_NAME", length = 50)
	public String getPanDocName() {
		return this.panDocName;
	}

	public void setPanDocName(String panDocName) {
		this.panDocName = panDocName;
	}

	@Column(name = "PAN_DOC")
	public Blob getPanDoc() {
		return this.panDoc;
	}

	public void setPanDoc(Blob panDoc) {
		this.panDoc = panDoc;
	}

	@Column(name = "BNK_PROF_NAME", length = 50)
	public String getBnkProfName() {
		return this.bnkProfName;
	}

	public void setBnkProfName(String bnkProfName) {
		this.bnkProfName = bnkProfName;
	}

	@Column(name = "BNK_PROF_DOC")
	public Blob getBnkProfDoc() {
		return this.bnkProfDoc;
	}

	public void setBnkProfDoc(Blob bnkProfDoc) {
		this.bnkProfDoc = bnkProfDoc;
	}

	@Column(name = "BNK_PROF_TYPE", length = 50)
	public String getBnkProfType() {
		return this.bnkProfType;
	}

	public void setBnkProfType(String bnkProfType) {
		this.bnkProfType = bnkProfType;
	}

	@Column(name = "PROFILE_PIC_NAME", length = 50)
	public String getProfilePicName() {
		return this.profilePicName;
	}

	public void setProfilePicName(String profilePicName) {
		this.profilePicName = profilePicName;
	}

	@Column(name = "PROFILE_PIC_DOC")
	public Blob getProfilePicDoc() {
		return this.profilePicDoc;
	}

	public void setProfilePicDoc(Blob profilePicDoc) {
		this.profilePicDoc = profilePicDoc;
	}

	@Column(name = "MASTER_FRANS_ID", length = 50)
	public String getMasterFransId() {
		return this.masterFransId;
	}

	public void setMasterFransId(String masterFransId) {
		this.masterFransId = masterFransId;
	}

	@Column(name = "CLUSTER_HEAD_ID", length = 50)
	public String getClusterHeadId() {
		return this.clusterHeadId;
	}

	public void setClusterHeadId(String clusterHeadId) {
		this.clusterHeadId = clusterHeadId;
	}

	@Column(name = "BANK_HOLDER_NAME", length = 50)
	public String getBankHolderName() {
		return this.bankHolderName;
	}

	public void setBankHolderName(String bankHolderName) {
		this.bankHolderName = bankHolderName;
	}

	@Column(name = "BANK_NAME", length = 50)
	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	@Column(name = "BANK_ACCT_NMBR", length = 50)
	public String getBankAcctNmbr() {
		return this.bankAcctNmbr;
	}

	public void setBankAcctNmbr(String bankAcctNmbr) {
		this.bankAcctNmbr = bankAcctNmbr;
	}

	@Column(name = "BANK_IFSC_CODE", length = 50)
	public String getBankIfscCode() {
		return this.bankIfscCode;
	}

	public void setBankIfscCode(String bankIfscCode) {
		this.bankIfscCode = bankIfscCode;
	}

	@Column(name = "AGENT_TYPE", length = 50)
	public String getAgentType() {
		return this.agentType;
	}

	public void setAgentType(String agentType) {
		this.agentType = agentType;
	}

	@Column(name = "RELATION_WITH_COMPANY", length = 10)
	public String getRelationWithCompany() {
		return this.relationWithCompany;
	}

	public void setRelationWithCompany(String relationWithCompany) {
		this.relationWithCompany = relationWithCompany;
	}

	@Column(name = "REMARKS", length = 100)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "EMPLOYEE_NO", length = 50)
	public String getEmployeeNo() {
		return this.employeeNo;
	}

	public void setEmployeeNo(String employeeNo) {
		this.employeeNo = employeeNo;
	}

	@Column(name = "PHY_HANDICAPPED", length = 10)
	public String getPhyHandicapped() {
		return this.phyHandicapped;
	}

	public void setPhyHandicapped(String phyHandicapped) {
		this.phyHandicapped = phyHandicapped;
	}

	@Column(name = "CATEGORY", length = 30)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "DELIVERY_CATEGORY", length = 50)
	public String getDeliveryCategory() {
		return this.deliveryCategory;
	}

	public void setDeliveryCategory(String deliveryCategory) {
		this.deliveryCategory = deliveryCategory;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserAdditionalDetailsId))
			return false;
		UserAdditionalDetailsId castOther = (UserAdditionalDetailsId) other;

		return ((this.getSeqId() == castOther.getSeqId()) || (this.getSeqId() != null && castOther.getSeqId() != null
				&& this.getSeqId().equals(castOther.getSeqId())))
				&& ((this.getUserId() == castOther.getUserId()) || (this.getUserId() != null
						&& castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())))
				&& ((this.getFirstName() == castOther.getFirstName()) || (this.getFirstName() != null
						&& castOther.getFirstName() != null && this.getFirstName().equals(castOther.getFirstName())))
				&& ((this.getMiddleName() == castOther.getMiddleName()) || (this.getMiddleName() != null
						&& castOther.getMiddleName() != null && this.getMiddleName().equals(castOther.getMiddleName())))
				&& ((this.getLastName() == castOther.getLastName()) || (this.getLastName() != null
						&& castOther.getLastName() != null && this.getLastName().equals(castOther.getLastName())))
				&& ((this.getUserName() == castOther.getUserName()) || (this.getUserName() != null
						&& castOther.getUserName() != null && this.getUserName().equals(castOther.getUserName())))
				&& ((this.getGender() == castOther.getGender()) || (this.getGender() != null
						&& castOther.getGender() != null && this.getGender().equals(castOther.getGender())))
				&& ((this.getDob() == castOther.getDob()) || (this.getDob() != null && castOther.getDob() != null
						&& this.getDob().equals(castOther.getDob())))
				&& ((this.getFatherName() == castOther.getFatherName()) || (this.getFatherName() != null
						&& castOther.getFatherName() != null && this.getFatherName().equals(castOther.getFatherName())))
				&& ((this.getAddrLneOne() == castOther.getAddrLneOne()) || (this.getAddrLneOne() != null
						&& castOther.getAddrLneOne() != null && this.getAddrLneOne().equals(castOther.getAddrLneOne())))
				&& ((this.getAddrLneTwo() == castOther.getAddrLneTwo()) || (this.getAddrLneTwo() != null
						&& castOther.getAddrLneTwo() != null && this.getAddrLneTwo().equals(castOther.getAddrLneTwo())))
				&& ((this.getLocality() == castOther.getLocality()) || (this.getLocality() != null
						&& castOther.getLocality() != null && this.getLocality().equals(castOther.getLocality())))
				&& ((this.getState() == castOther.getState()) || (this.getState() != null
						&& castOther.getState() != null && this.getState().equals(castOther.getState())))
				&& ((this.getDistrict() == castOther.getDistrict()) || (this.getDistrict() != null
						&& castOther.getDistrict() != null && this.getDistrict().equals(castOther.getDistrict())))
				&& ((this.getPincode() == castOther.getPincode()) || (this.getPincode() != null
						&& castOther.getPincode() != null && this.getPincode().equals(castOther.getPincode())))
				&& ((this.getCreatedOn() == castOther.getCreatedOn()) || (this.getCreatedOn() != null
						&& castOther.getCreatedOn() != null && this.getCreatedOn().equals(castOther.getCreatedOn())))
				&& ((this.getModifiedOn() == castOther.getModifiedOn()) || (this.getModifiedOn() != null
						&& castOther.getModifiedOn() != null && this.getModifiedOn().equals(castOther.getModifiedOn())))
				&& ((this.getProfAdsDocName() == castOther.getProfAdsDocName())
						|| (this.getProfAdsDocName() != null && castOther.getProfAdsDocName() != null
								&& this.getProfAdsDocName().equals(castOther.getProfAdsDocName())))
				&& ((this.getProfAdsDoc() == castOther.getProfAdsDoc()) || (this.getProfAdsDoc() != null
						&& castOther.getProfAdsDoc() != null && this.getProfAdsDoc().equals(castOther.getProfAdsDoc())))
				&& ((this.getProfAdsType() == castOther.getProfAdsType())
						|| (this.getProfAdsType() != null && castOther.getProfAdsType() != null
								&& this.getProfAdsType().equals(castOther.getProfAdsType())))
				&& ((this.getPanNumber() == castOther.getPanNumber()) || (this.getPanNumber() != null
						&& castOther.getPanNumber() != null && this.getPanNumber().equals(castOther.getPanNumber())))
				&& ((this.getPanDocName() == castOther.getPanDocName()) || (this.getPanDocName() != null
						&& castOther.getPanDocName() != null && this.getPanDocName().equals(castOther.getPanDocName())))
				&& ((this.getPanDoc() == castOther.getPanDoc()) || (this.getPanDoc() != null
						&& castOther.getPanDoc() != null && this.getPanDoc().equals(castOther.getPanDoc())))
				&& ((this.getBnkProfName() == castOther.getBnkProfName())
						|| (this.getBnkProfName() != null && castOther.getBnkProfName() != null
								&& this.getBnkProfName().equals(castOther.getBnkProfName())))
				&& ((this.getBnkProfDoc() == castOther.getBnkProfDoc()) || (this.getBnkProfDoc() != null
						&& castOther.getBnkProfDoc() != null && this.getBnkProfDoc().equals(castOther.getBnkProfDoc())))
				&& ((this.getBnkProfType() == castOther.getBnkProfType())
						|| (this.getBnkProfType() != null && castOther.getBnkProfType() != null
								&& this.getBnkProfType().equals(castOther.getBnkProfType())))
				&& ((this.getProfilePicName() == castOther.getProfilePicName())
						|| (this.getProfilePicName() != null && castOther.getProfilePicName() != null
								&& this.getProfilePicName().equals(castOther.getProfilePicName())))
				&& ((this.getProfilePicDoc() == castOther.getProfilePicDoc())
						|| (this.getProfilePicDoc() != null && castOther.getProfilePicDoc() != null
								&& this.getProfilePicDoc().equals(castOther.getProfilePicDoc())))
				&& ((this.getMasterFransId() == castOther.getMasterFransId())
						|| (this.getMasterFransId() != null && castOther.getMasterFransId() != null
								&& this.getMasterFransId().equals(castOther.getMasterFransId())))
				&& ((this.getClusterHeadId() == castOther.getClusterHeadId())
						|| (this.getClusterHeadId() != null && castOther.getClusterHeadId() != null
								&& this.getClusterHeadId().equals(castOther.getClusterHeadId())))
				&& ((this.getBankHolderName() == castOther.getBankHolderName())
						|| (this.getBankHolderName() != null && castOther.getBankHolderName() != null
								&& this.getBankHolderName().equals(castOther.getBankHolderName())))
				&& ((this.getBankName() == castOther.getBankName()) || (this.getBankName() != null
						&& castOther.getBankName() != null && this.getBankName().equals(castOther.getBankName())))
				&& ((this.getBankAcctNmbr() == castOther.getBankAcctNmbr())
						|| (this.getBankAcctNmbr() != null && castOther.getBankAcctNmbr() != null
								&& this.getBankAcctNmbr().equals(castOther.getBankAcctNmbr())))
				&& ((this.getBankIfscCode() == castOther.getBankIfscCode())
						|| (this.getBankIfscCode() != null && castOther.getBankIfscCode() != null
								&& this.getBankIfscCode().equals(castOther.getBankIfscCode())))
				&& ((this.getAgentType() == castOther.getAgentType()) || (this.getAgentType() != null
						&& castOther.getAgentType() != null && this.getAgentType().equals(castOther.getAgentType())))
				&& ((this.getRelationWithCompany() == castOther.getRelationWithCompany())
						|| (this.getRelationWithCompany() != null && castOther.getRelationWithCompany() != null
								&& this.getRelationWithCompany().equals(castOther.getRelationWithCompany())))
				&& ((this.getRemarks() == castOther.getRemarks()) || (this.getRemarks() != null
						&& castOther.getRemarks() != null && this.getRemarks().equals(castOther.getRemarks())))
				&& ((this.getEmployeeNo() == castOther.getEmployeeNo()) || (this.getEmployeeNo() != null
						&& castOther.getEmployeeNo() != null && this.getEmployeeNo().equals(castOther.getEmployeeNo())))
				&& ((this.getPhyHandicapped() == castOther.getPhyHandicapped())
						|| (this.getPhyHandicapped() != null && castOther.getPhyHandicapped() != null
								&& this.getPhyHandicapped().equals(castOther.getPhyHandicapped())))
				&& ((this.getCategory() == castOther.getCategory()) || (this.getCategory() != null
						&& castOther.getCategory() != null && this.getCategory().equals(castOther.getCategory())))
				&& ((this.getDeliveryCategory() == castOther.getDeliveryCategory())
						|| (this.getDeliveryCategory() != null && castOther.getDeliveryCategory() != null
								&& this.getDeliveryCategory().equals(castOther.getDeliveryCategory())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getSeqId() == null ? 0 : this.getSeqId().hashCode());
		result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result + (getFirstName() == null ? 0 : this.getFirstName().hashCode());
		result = 37 * result + (getMiddleName() == null ? 0 : this.getMiddleName().hashCode());
		result = 37 * result + (getLastName() == null ? 0 : this.getLastName().hashCode());
		result = 37 * result + (getUserName() == null ? 0 : this.getUserName().hashCode());
		result = 37 * result + (getGender() == null ? 0 : this.getGender().hashCode());
		result = 37 * result + (getDob() == null ? 0 : this.getDob().hashCode());
		result = 37 * result + (getFatherName() == null ? 0 : this.getFatherName().hashCode());
		result = 37 * result + (getAddrLneOne() == null ? 0 : this.getAddrLneOne().hashCode());
		result = 37 * result + (getAddrLneTwo() == null ? 0 : this.getAddrLneTwo().hashCode());
		result = 37 * result + (getLocality() == null ? 0 : this.getLocality().hashCode());
		result = 37 * result + (getState() == null ? 0 : this.getState().hashCode());
		result = 37 * result + (getDistrict() == null ? 0 : this.getDistrict().hashCode());
		result = 37 * result + (getPincode() == null ? 0 : this.getPincode().hashCode());
		result = 37 * result + (getCreatedOn() == null ? 0 : this.getCreatedOn().hashCode());
		result = 37 * result + (getModifiedOn() == null ? 0 : this.getModifiedOn().hashCode());
		result = 37 * result + (getProfAdsDocName() == null ? 0 : this.getProfAdsDocName().hashCode());
		result = 37 * result + (getProfAdsDoc() == null ? 0 : this.getProfAdsDoc().hashCode());
		result = 37 * result + (getProfAdsType() == null ? 0 : this.getProfAdsType().hashCode());
		result = 37 * result + (getPanNumber() == null ? 0 : this.getPanNumber().hashCode());
		result = 37 * result + (getPanDocName() == null ? 0 : this.getPanDocName().hashCode());
		result = 37 * result + (getPanDoc() == null ? 0 : this.getPanDoc().hashCode());
		result = 37 * result + (getBnkProfName() == null ? 0 : this.getBnkProfName().hashCode());
		result = 37 * result + (getBnkProfDoc() == null ? 0 : this.getBnkProfDoc().hashCode());
		result = 37 * result + (getBnkProfType() == null ? 0 : this.getBnkProfType().hashCode());
		result = 37 * result + (getProfilePicName() == null ? 0 : this.getProfilePicName().hashCode());
		result = 37 * result + (getProfilePicDoc() == null ? 0 : this.getProfilePicDoc().hashCode());
		result = 37 * result + (getMasterFransId() == null ? 0 : this.getMasterFransId().hashCode());
		result = 37 * result + (getClusterHeadId() == null ? 0 : this.getClusterHeadId().hashCode());
		result = 37 * result + (getBankHolderName() == null ? 0 : this.getBankHolderName().hashCode());
		result = 37 * result + (getBankName() == null ? 0 : this.getBankName().hashCode());
		result = 37 * result + (getBankAcctNmbr() == null ? 0 : this.getBankAcctNmbr().hashCode());
		result = 37 * result + (getBankIfscCode() == null ? 0 : this.getBankIfscCode().hashCode());
		result = 37 * result + (getAgentType() == null ? 0 : this.getAgentType().hashCode());
		result = 37 * result + (getRelationWithCompany() == null ? 0 : this.getRelationWithCompany().hashCode());
		result = 37 * result + (getRemarks() == null ? 0 : this.getRemarks().hashCode());
		result = 37 * result + (getEmployeeNo() == null ? 0 : this.getEmployeeNo().hashCode());
		result = 37 * result + (getPhyHandicapped() == null ? 0 : this.getPhyHandicapped().hashCode());
		result = 37 * result + (getCategory() == null ? 0 : this.getCategory().hashCode());
		result = 37 * result + (getDeliveryCategory() == null ? 0 : this.getDeliveryCategory().hashCode());
		return result;
	}

}
